### ISSUE TITLE
не собирается проект((

### ISSUE THREAD

**Issue by PesterevValery** [teplofizik/nyaprogrammer#1]
не собирается проект(( Помогите, пожалуйста.  Использую Microsoft Visual Studio Community 2019

**Comment by teplofizik** [comment]
Хм, я проверю. Но если что, есть вторая версия проекта, переделанная: https://github.com/teplofizik/nyaprog

**Comment by teplofizik** [comment]
Вроде, поправил зависимости, попробуйте ещё раз

**Comment by PesterevValery** [comment]
Сейчас все хорошо. Спасибо!
